
## YAML Template.
--- 
#spring:
 #   application:
  #      name: canteen     
   # cloud:
    #    config:
     #       server:
      #          bootstrap:  true
          #      prefix: /config
          #      git:
           #         uri: http://gitsrvr/configs/hmsconfigs.git
           #         basedir:    /data/${spring.application.name}/config-git
            #        force-pull: true
                    
server.port: 1080
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
#spring.datasource.url: jdbc:mysql://192.200.10.15:3306/hmsdev?useSSL=false
spring.datasource.url: jdbc:mysql://localhost:3306/canteen?useSSL=false
spring.datasource.username: root
spring.datasource.password: password


#spring.datasource.url: jdbc:sqlserver://192.200.10.110;databaseName=canteen
#spring.jpa.properties.hibernate.dialect :  org.hibernate.dialect.SQLServer2012Dialect
#spring.jpa.database-platform:  org.hibernate.dialect.SQLServer2012Dialect
#spring.datasource.type: com.zaxxer.hikari.HikariDataSource
#spring.datasource.hikari.maximum-pool-size: 50
#spring.datasource.hikari.minimum-idle: 2
#spring.datasource.hikari.idle-timeout: 180000
#spring.datasource.username: HISADMIN
#spring.datasource.password: 5p1tf1r3
spring.jpa.properties.hibernate.id.new_generator_mappings :  false
spring.jpa.properties.hibernate.show_sql :  false
spring.jpa.properties.hibernate.format_sql :  true





#
##spring.jpa.properties.hibernate.dialect :  org.hibernate.dialect.MySQLDialect
#

spring.jpa.hibernate.ddl-auto :  update
logging.file: /data/canteen/log/canteen-web.log
spring.http.multipart.max-file-size: 50MB




                   