
## YAML Template.
--- 
#spring:
 #   application:
  #      name: canteen     
   # cloud:
    #    config:
     #       server:
      #          bootstrap:  true
          #      prefix: /config
          #      git:
           #         uri: http://gitsrvr/configs/hmsconfigs.git
           #         basedir:    /data/${spring.application.name}/config-git
            #        force-pull: true
                    
server.port: 1080
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
##spring.datasource.url: jdbc:mysql://192.200.10.15:3306/hmsdev?useSSL=false
spring.datasource.url: jdbc:mysql://localhost:3306/canteen?useSSL=false
spring.datasource.username: root
spring.datasource.password: password
##spring.datasource.url: jdbc:sqlserver://192.200.1.50;databaseName=HMSWarehouseTest
##spring.datasource.username: hms
##spring.datasource.password: '@Access123'
##spring.jpa.properties.hibernate.dialect :  org.hibernate.dialect.SQLServer2012Dialect
spring.datasource.tomcat.max-wait: 20000
spring.datasource.tomcat.max-active: 50
spring.datasource.tomcat.max-idle: 20
spring.datasource.tomcat.min-idle: 15
#
##spring.jpa.properties.hibernate.dialect :  org.hibernate.dialect.MySQLDialect
#
spring.jpa.properties.hibernate.id.new_generator_mappings :  false
spring.jpa.properties.hibernate.show_sql :  false
spring.jpa.properties.hibernate.format_sql :  true
spring.jpa.hibernate.ddl-auto :  update
logging.file: /data/hms/log/hms-web.log
spring.http.multipart.max-file-size: 50MB
hms:rabbit.smsque:  smsque
hms.rabbit.emailque: emailque1 





                   